const Courses = 
    [
        {
          "id": 1,
          "title": "Introduction to Information Technology",
          "image": require("../../assets/image/ifoTech.jpeg"),
          "description": "A comprehensive introduction to the field of Information Technology.",
          "course1": "Programming Fundamentals",
          "course2": "Database Management",
          "course3": "Network Basics",
          "img1":require("../../assets/image/img11.jpeg"),
          "img2":require("../../assets/image/img12.png"),
          "img3":require("../../assets/image/img13.jpeg"),
          "price": 4999,
          "websiteLink1": 'https://www.educative.io/answers/what-are-the-basic-fundamental-concepts-of-programming',
          "websiteLink2": 'https://www.geeksforgeeks.org/introduction-of-dbms-database-management-system-set-1/',
          "websiteLink3": 'https://www.geeksforgeeks.org/basics-computer-networking/',
        },
        {
          "id": 2,
          "title": "Web Development Essentials",
          "image": require("../../assets/image/web.jpeg"),
          "description": "Learn the fundamentals of web development and design.",
          "course1": "HTML and CSS",
          "course2": "JavaScript Basics",
          "course3": "Responsive Web Design",
          "img1":require("../../assets/image/img21.png"),
          "img2":require("../../assets/image/img22.jpg"),
          "img3":require("../../assets/image/img23.png"),
          "price": 5999,
          "websiteLink1":'https://www.w3schools.com/html/html_css.asp',
          "websiteLink2":'https://www.w3schools.com/js/',
          "websiteLink3":'https://www.w3schools.com/html/html_responsive.asp',
        },
        {
          "id": 3,
          "title": "Cybersecurity Basics",
          "image": require("../../assets/image/cyber.jpeg"),
          "description": "Explore the foundational principles of cybersecurity.",
          "course1": "Network Security",
          "course2": "Ethical Hacking",
          "course3": "Data Encryption",
          "img1":require("../../assets/image/img31.jpeg"),
          "img2":require("../../assets/image/img32.jpeg"),
          "img3":require("../../assets/image/img33.png"),
          "price": 6999,
          "websiteLink1":'https://www.geeksforgeeks.org/network-security/',
          "websiteLink2":'https://www.eccouncil.org/cybersecurity-exchange/ethical-hacking/what-is-ethical-hacking/#:~:text=Ethical%20hacking%20is%20a%20process,and%20looking%20for%20weak%20points.',
          "websiteLink3":'https://www.geeksforgeeks.org/what-is-data-encryption/'
        },
        {
          "id": 4,
          "title": "Data Science Fundamentals",
          "image": require("../../assets/image/ds.jpeg"),
          "description": "An introduction to the world of data science and analytics.",
          "course1": "Data Analysis with Python",
          "course2": "Machine Learning Basics",
          "course3": "Data Visualization",
          "img1":require("../../assets/image/img41.jpeg"),
          "img2":require("../../assets/image/img42.jpeg"),
          "img3":require("../../assets/image/img43.jpeg"),
          "price": 7999,
          "websiteLink1":'https://www.geeksforgeeks.org/data-analysis-with-python/',
          "websiteLink2":'https://www.geeksforgeeks.org/machine-learning/',
          "websiteLink3":'https://www.geeksforgeeks.org/data-visualization-and-its-importance/',
        },
        {
          "id": 5,
          "title": "Cloud Computing Essentials",
          "image": require("../../assets/image/cloud.jpeg"),
          "description": "Understand the basics of cloud computing and services.",
          "course1": "Cloud Infrastructure",
          "course2": "AWS Fundamentals",
          "course3": "Azure Basics",
          "img1":require("../../assets/image/img51.jpeg"),
          "img2":require("../../assets/image/img52.jpeg"),
          "img3":require("../../assets/image/img53.jpeg"),
          "price": 8999,
          "websiteLink1":'https://www.techtarget.com/searchcloudcomputing/definition/cloud-infrastructure',
          "websiteLink2":'https://www.w3schools.com/aws/aws_specialization_aws_fundamentals.php',
          "websiteLink3":'https://www.koenig-solutions.com/blog/what-is-microsoft-azure-fundamentals'
        },
        {
          "id": 6,
          "title": "Mobile App Development",
          "image": require("../../assets/image/appdev.jpeg"),
          "description": "Learn to develop mobile applications for iOS and Android.",
          "course1": "Mobile App Design",
          "course2": "iOS Development",
          "course3": "Android Development",
          "img1":require("../../assets/image/img61.jpeg"),
          "img2":require("../../assets/image/img62.png"),
          "img3":require("../../assets/image/img63.jpeg"),
          "price": 9999,
          "websiteLink1":'https://www.geeksforgeeks.org/introduction-of-mobile-applications/',
          "websiteLink2":'https://www.geeksforgeeks.org/getting-started-with-ios-development/',
          "websiteLink3":'https://www.geeksforgeeks.org/android-tutorial/',
        },
      ];

      export default Courses;